# Generated by Django 3.1.1 on 2023-06-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=1000)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
